site_name: Postgres Operator
repo_url: https://github.com/zalando/postgres-operator
theme: readthedocs

nav:
  - index.md
  - quickstart.md
  - operator-ui.md
  - administrator.md
  - user.md
  - developer.md
  - Reference:
    - reference/operator_parameters.md
    - reference/cluster_manifest.md
    - reference/command_line_and_environment.md
