apiVersion: "acid.zalan.do/v1"
kind: "Spilo"

metadata:
  name: testcluster

spec:
  docker_image: registry.opensource.zalan.do/acid/spilo-9.6:1.2-p9
  etcd_host: etcd-client.default.svc.cluster.local:2379
  volume_size: 100 # GB
  resource_cpu: 100m
  resource_memory: 500Mi
  number_of_instances: 3
  postgres_configuration:
  - param: "max_connections"
    value: "10"
  - param: "shared_buffers"
    value: "500MB"
