apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: acid
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      containers:
      - name: postgres-operator
        image: postgres-operator:0.1
