apiVersion: "acid.zalan.do/v1"
kind: "Postgresql"

metadata:
  name: testcluster

spec:
  volume:
    size: 100Gi
    storageClass: gp2
  numberOfInstances: 2
  postgresql:
    version: "9.6"
    parameters:
      shared_buffers: "500MB"
      max_connections: "10"
      log_statement: "all"
  users:
    jdoe:
    - superuser
    - createdb
    rmiles:
    rroe:
  resources:
    cpu: 100m
    memory: 500Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5
    ttl: 30
    loop_wait: &loop_wait 10
    retry_timeout: 10
    maximum_lag_on_failover: 33554432
  maintenanceWindows:
  - 01:00-06:00 #UTC
  - Sat:00:00-Sat:04:00
